# Generated by Django 5.0.2 on 2024-11-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Diet', 'Diet'), ('Fitness', 'Fitness'), ('Medical', 'Medical'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
